#playbook that runs simple show commands using the cisco module

---
- name: Show version and other user level commands
  hosts: all
  order: sorted
  connection: local
  gather_facts: false
  
  tasks:
    - name: run mutlitple commands on remote devices
      ios_command:
        commands:
          - show version
          - show ip int brief
      register: print_output
      
    - name: print the output
      debug:  
        var: print_output.stdout_lines
        
        
#Command to run:
#ansible-playbook ciscoshow.yml -u <your username> -k